// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Piro.FhirServer.Application.Repository;

#nullable disable

namespace Piro.FhirServer.Application.Repository.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20221001112444_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Piro.FhirServer.Application.Domain.Models.IndexReference", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("FhirId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ResourceStoreId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("SearchParameterId")
                        .HasColumnType("integer");

                    b.Property<int?>("TargetResourceStoreId")
                        .HasColumnType("integer");

                    b.Property<string>("VersionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FhirId");

                    b.HasIndex("ResourceStoreId");

                    b.HasIndex("ResourceTypeId");

                    b.HasIndex("TargetResourceStoreId");

                    b.ToTable("IndexReference");
                });

            modelBuilder.Entity("Piro.FhirServer.Application.Domain.Models.IndexString", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<int?>("ResourceStoreId")
                        .IsRequired()
                        .HasColumnType("integer");

                    b.Property<int>("SearchParameterId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ResourceStoreId");

                    b.HasIndex("Value");

                    b.ToTable("IndexString");
                });

            modelBuilder.Entity("Piro.FhirServer.Application.Domain.Models.ResourceStore", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("FhirId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ResourceTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FhirId");

                    b.HasIndex("ResourceTypeId");

                    b.ToTable("ResourceStore");
                });

            modelBuilder.Entity("Piro.FhirServer.Application.Domain.Models.ResourceType", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int?>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ResourceType");
                });

            modelBuilder.Entity("Piro.FhirServer.Application.Domain.Models.IndexReference", b =>
                {
                    b.HasOne("Piro.FhirServer.Application.Domain.Models.ResourceStore", "ResourceStore")
                        .WithMany("ReferenceIndexList")
                        .HasForeignKey("ResourceStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Piro.FhirServer.Application.Domain.Models.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Piro.FhirServer.Application.Domain.Models.ResourceStore", "TargetResourceStore")
                        .WithMany("BackResourceReferenceIndexList")
                        .HasForeignKey("TargetResourceStoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ResourceStore");

                    b.Navigation("ResourceType");

                    b.Navigation("TargetResourceStore");
                });

            modelBuilder.Entity("Piro.FhirServer.Application.Domain.Models.IndexString", b =>
                {
                    b.HasOne("Piro.FhirServer.Application.Domain.Models.ResourceStore", "ResourceStore")
                        .WithMany("StringIndexList")
                        .HasForeignKey("ResourceStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResourceStore");
                });

            modelBuilder.Entity("Piro.FhirServer.Application.Domain.Models.ResourceStore", b =>
                {
                    b.HasOne("Piro.FhirServer.Application.Domain.Models.ResourceType", "ResourceType")
                        .WithMany()
                        .HasForeignKey("ResourceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ResourceType");
                });

            modelBuilder.Entity("Piro.FhirServer.Application.Domain.Models.ResourceStore", b =>
                {
                    b.Navigation("BackResourceReferenceIndexList");

                    b.Navigation("ReferenceIndexList");

                    b.Navigation("StringIndexList");
                });
#pragma warning restore 612, 618
        }
    }
}
