

//This class was auto code generated by a T4 Template found here: Bug.CodeGeneration.T4Templates.ResourceType: ResourceType.tt
//
// Last Generated : 7/10/2022 9:55:38 PM
//
using Piro.FhirServer.Domain.Enums;
namespace Piro.FhirServer.Domain.Enums
{
  public enum ResourceType
  {
      [EnumInfo("Resource", "Resource")]
      Resource = 1,         
      [EnumInfo("DomainResource", "DomainResource")]
      DomainResource = 2,         
      [EnumInfo("Account", "Account")]
      Account = 3,         
      [EnumInfo("ActivityDefinition", "ActivityDefinition")]
      ActivityDefinition = 4,         
      [EnumInfo("AdverseEvent", "AdverseEvent")]
      AdverseEvent = 5,         
      [EnumInfo("AllergyIntolerance", "AllergyIntolerance")]
      AllergyIntolerance = 6,         
      [EnumInfo("Appointment", "Appointment")]
      Appointment = 7,         
      [EnumInfo("AppointmentResponse", "AppointmentResponse")]
      AppointmentResponse = 8,         
      [EnumInfo("AuditEvent", "AuditEvent")]
      AuditEvent = 9,         
      [EnumInfo("Basic", "Basic")]
      Basic = 10,         
      [EnumInfo("Binary", "Binary")]
      Binary = 11,         
      [EnumInfo("BodySite", "BodySite")]
      BodySite = 12,         
      [EnumInfo("Bundle", "Bundle")]
      Bundle = 13,         
      [EnumInfo("CapabilityStatement", "CapabilityStatement")]
      CapabilityStatement = 14,         
      [EnumInfo("CarePlan", "CarePlan")]
      CarePlan = 15,         
      [EnumInfo("CareTeam", "CareTeam")]
      CareTeam = 16,         
      [EnumInfo("ChargeItem", "ChargeItem")]
      ChargeItem = 17,         
      [EnumInfo("Claim", "Claim")]
      Claim = 18,         
      [EnumInfo("ClaimResponse", "ClaimResponse")]
      ClaimResponse = 19,         
      [EnumInfo("ClinicalImpression", "ClinicalImpression")]
      ClinicalImpression = 20,         
      [EnumInfo("CodeSystem", "CodeSystem")]
      CodeSystem = 21,         
      [EnumInfo("Communication", "Communication")]
      Communication = 22,         
      [EnumInfo("CommunicationRequest", "CommunicationRequest")]
      CommunicationRequest = 23,         
      [EnumInfo("CompartmentDefinition", "CompartmentDefinition")]
      CompartmentDefinition = 24,         
      [EnumInfo("Composition", "Composition")]
      Composition = 25,         
      [EnumInfo("ConceptMap", "ConceptMap")]
      ConceptMap = 26,         
      [EnumInfo("Condition", "Condition")]
      Condition = 27,         
      [EnumInfo("Consent", "Consent")]
      Consent = 28,         
      [EnumInfo("Contract", "Contract")]
      Contract = 29,         
      [EnumInfo("Coverage", "Coverage")]
      Coverage = 30,         
      [EnumInfo("DataElement", "DataElement")]
      DataElement = 31,         
      [EnumInfo("DetectedIssue", "DetectedIssue")]
      DetectedIssue = 32,         
      [EnumInfo("Device", "Device")]
      Device = 33,         
      [EnumInfo("DeviceComponent", "DeviceComponent")]
      DeviceComponent = 34,         
      [EnumInfo("DeviceMetric", "DeviceMetric")]
      DeviceMetric = 35,         
      [EnumInfo("DeviceRequest", "DeviceRequest")]
      DeviceRequest = 36,         
      [EnumInfo("DeviceUseStatement", "DeviceUseStatement")]
      DeviceUseStatement = 37,         
      [EnumInfo("DiagnosticReport", "DiagnosticReport")]
      DiagnosticReport = 38,         
      [EnumInfo("DocumentManifest", "DocumentManifest")]
      DocumentManifest = 39,         
      [EnumInfo("DocumentReference", "DocumentReference")]
      DocumentReference = 40,         
      [EnumInfo("EligibilityRequest", "EligibilityRequest")]
      EligibilityRequest = 41,         
      [EnumInfo("EligibilityResponse", "EligibilityResponse")]
      EligibilityResponse = 42,         
      [EnumInfo("Encounter", "Encounter")]
      Encounter = 43,         
      [EnumInfo("Endpoint", "Endpoint")]
      Endpoint = 44,         
      [EnumInfo("EnrollmentRequest", "EnrollmentRequest")]
      EnrollmentRequest = 45,         
      [EnumInfo("EnrollmentResponse", "EnrollmentResponse")]
      EnrollmentResponse = 46,         
      [EnumInfo("EpisodeOfCare", "EpisodeOfCare")]
      EpisodeOfCare = 47,         
      [EnumInfo("ExpansionProfile", "ExpansionProfile")]
      ExpansionProfile = 48,         
      [EnumInfo("ExplanationOfBenefit", "ExplanationOfBenefit")]
      ExplanationOfBenefit = 49,         
      [EnumInfo("FamilyMemberHistory", "FamilyMemberHistory")]
      FamilyMemberHistory = 50,         
      [EnumInfo("Flag", "Flag")]
      Flag = 51,         
      [EnumInfo("Goal", "Goal")]
      Goal = 52,         
      [EnumInfo("GraphDefinition", "GraphDefinition")]
      GraphDefinition = 53,         
      [EnumInfo("Group", "Group")]
      Group = 54,         
      [EnumInfo("GuidanceResponse", "GuidanceResponse")]
      GuidanceResponse = 55,         
      [EnumInfo("HealthcareService", "HealthcareService")]
      HealthcareService = 56,         
      [EnumInfo("ImagingManifest", "ImagingManifest")]
      ImagingManifest = 57,         
      [EnumInfo("ImagingStudy", "ImagingStudy")]
      ImagingStudy = 58,         
      [EnumInfo("Immunization", "Immunization")]
      Immunization = 59,         
      [EnumInfo("ImmunizationRecommendation", "ImmunizationRecommendation")]
      ImmunizationRecommendation = 60,         
      [EnumInfo("ImplementationGuide", "ImplementationGuide")]
      ImplementationGuide = 61,         
      [EnumInfo("Library", "Library")]
      Library = 62,         
      [EnumInfo("Linkage", "Linkage")]
      Linkage = 63,         
      [EnumInfo("List", "List")]
      List = 64,         
      [EnumInfo("Location", "Location")]
      Location = 65,         
      [EnumInfo("Measure", "Measure")]
      Measure = 66,         
      [EnumInfo("MeasureReport", "MeasureReport")]
      MeasureReport = 67,         
      [EnumInfo("Media", "Media")]
      Media = 68,         
      [EnumInfo("Medication", "Medication")]
      Medication = 69,         
      [EnumInfo("MedicationAdministration", "MedicationAdministration")]
      MedicationAdministration = 70,         
      [EnumInfo("MedicationDispense", "MedicationDispense")]
      MedicationDispense = 71,         
      [EnumInfo("MedicationRequest", "MedicationRequest")]
      MedicationRequest = 72,         
      [EnumInfo("MedicationStatement", "MedicationStatement")]
      MedicationStatement = 73,         
      [EnumInfo("MessageDefinition", "MessageDefinition")]
      MessageDefinition = 74,         
      [EnumInfo("MessageHeader", "MessageHeader")]
      MessageHeader = 75,         
      [EnumInfo("NamingSystem", "NamingSystem")]
      NamingSystem = 76,         
      [EnumInfo("NutritionOrder", "NutritionOrder")]
      NutritionOrder = 77,         
      [EnumInfo("Observation", "Observation")]
      Observation = 78,         
      [EnumInfo("OperationDefinition", "OperationDefinition")]
      OperationDefinition = 79,         
      [EnumInfo("OperationOutcome", "OperationOutcome")]
      OperationOutcome = 80,         
      [EnumInfo("Organization", "Organization")]
      Organization = 81,         
      [EnumInfo("Parameters", "Parameters")]
      Parameters = 82,         
      [EnumInfo("Patient", "Patient")]
      Patient = 83,         
      [EnumInfo("PaymentNotice", "PaymentNotice")]
      PaymentNotice = 84,         
      [EnumInfo("PaymentReconciliation", "PaymentReconciliation")]
      PaymentReconciliation = 85,         
      [EnumInfo("Person", "Person")]
      Person = 86,         
      [EnumInfo("PlanDefinition", "PlanDefinition")]
      PlanDefinition = 87,         
      [EnumInfo("Practitioner", "Practitioner")]
      Practitioner = 88,         
      [EnumInfo("PractitionerRole", "PractitionerRole")]
      PractitionerRole = 89,         
      [EnumInfo("Procedure", "Procedure")]
      Procedure = 90,         
      [EnumInfo("ProcedureRequest", "ProcedureRequest")]
      ProcedureRequest = 91,         
      [EnumInfo("ProcessRequest", "ProcessRequest")]
      ProcessRequest = 92,         
      [EnumInfo("ProcessResponse", "ProcessResponse")]
      ProcessResponse = 93,         
      [EnumInfo("Provenance", "Provenance")]
      Provenance = 94,         
      [EnumInfo("Questionnaire", "Questionnaire")]
      Questionnaire = 95,         
      [EnumInfo("QuestionnaireResponse", "QuestionnaireResponse")]
      QuestionnaireResponse = 96,         
      [EnumInfo("ReferralRequest", "ReferralRequest")]
      ReferralRequest = 97,         
      [EnumInfo("RelatedPerson", "RelatedPerson")]
      RelatedPerson = 98,         
      [EnumInfo("RequestGroup", "RequestGroup")]
      RequestGroup = 99,         
      [EnumInfo("ResearchStudy", "ResearchStudy")]
      ResearchStudy = 100,         
      [EnumInfo("ResearchSubject", "ResearchSubject")]
      ResearchSubject = 101,         
      [EnumInfo("RiskAssessment", "RiskAssessment")]
      RiskAssessment = 102,         
      [EnumInfo("Schedule", "Schedule")]
      Schedule = 103,         
      [EnumInfo("SearchParameter", "SearchParameter")]
      SearchParameter = 104,         
      [EnumInfo("Sequence", "Sequence")]
      Sequence = 105,         
      [EnumInfo("ServiceDefinition", "ServiceDefinition")]
      ServiceDefinition = 106,         
      [EnumInfo("Slot", "Slot")]
      Slot = 107,         
      [EnumInfo("Specimen", "Specimen")]
      Specimen = 108,         
      [EnumInfo("StructureDefinition", "StructureDefinition")]
      StructureDefinition = 109,         
      [EnumInfo("StructureMap", "StructureMap")]
      StructureMap = 110,         
      [EnumInfo("Subscription", "Subscription")]
      Subscription = 111,         
      [EnumInfo("Substance", "Substance")]
      Substance = 112,         
      [EnumInfo("SupplyDelivery", "SupplyDelivery")]
      SupplyDelivery = 113,         
      [EnumInfo("SupplyRequest", "SupplyRequest")]
      SupplyRequest = 114,         
      [EnumInfo("Task", "Task")]
      Task = 115,         
      [EnumInfo("TestReport", "TestReport")]
      TestReport = 116,         
      [EnumInfo("TestScript", "TestScript")]
      TestScript = 117,         
      [EnumInfo("ValueSet", "ValueSet")]
      ValueSet = 118,         
      [EnumInfo("VisionPrescription", "VisionPrescription")]
      VisionPrescription = 119,         
      [EnumInfo("BiologicallyDerivedProduct", "BiologicallyDerivedProduct")]
      BiologicallyDerivedProduct = 120,         
      [EnumInfo("BodyStructure", "BodyStructure")]
      BodyStructure = 121,         
      [EnumInfo("CatalogEntry", "CatalogEntry")]
      CatalogEntry = 122,         
      [EnumInfo("ChargeItemDefinition", "ChargeItemDefinition")]
      ChargeItemDefinition = 123,         
      [EnumInfo("CoverageEligibilityRequest", "CoverageEligibilityRequest")]
      CoverageEligibilityRequest = 124,         
      [EnumInfo("CoverageEligibilityResponse", "CoverageEligibilityResponse")]
      CoverageEligibilityResponse = 125,         
      [EnumInfo("DeviceDefinition", "DeviceDefinition")]
      DeviceDefinition = 126,         
      [EnumInfo("EffectEvidenceSynthesis", "EffectEvidenceSynthesis")]
      EffectEvidenceSynthesis = 127,         
      [EnumInfo("EventDefinition", "EventDefinition")]
      EventDefinition = 128,         
      [EnumInfo("Evidence", "Evidence")]
      Evidence = 129,         
      [EnumInfo("EvidenceVariable", "EvidenceVariable")]
      EvidenceVariable = 130,         
      [EnumInfo("ExampleScenario", "ExampleScenario")]
      ExampleScenario = 131,         
      [EnumInfo("ImmunizationEvaluation", "ImmunizationEvaluation")]
      ImmunizationEvaluation = 132,         
      [EnumInfo("InsurancePlan", "InsurancePlan")]
      InsurancePlan = 133,         
      [EnumInfo("Invoice", "Invoice")]
      Invoice = 134,         
      [EnumInfo("MedicationKnowledge", "MedicationKnowledge")]
      MedicationKnowledge = 135,         
      [EnumInfo("MedicinalProduct", "MedicinalProduct")]
      MedicinalProduct = 136,         
      [EnumInfo("MedicinalProductAuthorization", "MedicinalProductAuthorization")]
      MedicinalProductAuthorization = 137,         
      [EnumInfo("MedicinalProductContraindication", "MedicinalProductContraindication")]
      MedicinalProductContraindication = 138,         
      [EnumInfo("MedicinalProductIndication", "MedicinalProductIndication")]
      MedicinalProductIndication = 139,         
      [EnumInfo("MedicinalProductIngredient", "MedicinalProductIngredient")]
      MedicinalProductIngredient = 140,         
      [EnumInfo("MedicinalProductInteraction", "MedicinalProductInteraction")]
      MedicinalProductInteraction = 141,         
      [EnumInfo("MedicinalProductManufactured", "MedicinalProductManufactured")]
      MedicinalProductManufactured = 142,         
      [EnumInfo("MedicinalProductPackaged", "MedicinalProductPackaged")]
      MedicinalProductPackaged = 143,         
      [EnumInfo("MedicinalProductPharmaceutical", "MedicinalProductPharmaceutical")]
      MedicinalProductPharmaceutical = 144,         
      [EnumInfo("MedicinalProductUndesirableEffect", "MedicinalProductUndesirableEffect")]
      MedicinalProductUndesirableEffect = 145,         
      [EnumInfo("MolecularSequence", "MolecularSequence")]
      MolecularSequence = 146,         
      [EnumInfo("ObservationDefinition", "ObservationDefinition")]
      ObservationDefinition = 147,         
      [EnumInfo("OrganizationAffiliation", "OrganizationAffiliation")]
      OrganizationAffiliation = 148,         
      [EnumInfo("ResearchDefinition", "ResearchDefinition")]
      ResearchDefinition = 149,         
      [EnumInfo("ResearchElementDefinition", "ResearchElementDefinition")]
      ResearchElementDefinition = 150,         
      [EnumInfo("RiskEvidenceSynthesis", "RiskEvidenceSynthesis")]
      RiskEvidenceSynthesis = 151,         
      [EnumInfo("ServiceRequest", "ServiceRequest")]
      ServiceRequest = 152,         
      [EnumInfo("SpecimenDefinition", "SpecimenDefinition")]
      SpecimenDefinition = 153,         
      [EnumInfo("SubstanceNucleicAcid", "SubstanceNucleicAcid")]
      SubstanceNucleicAcid = 154,         
      [EnumInfo("SubstancePolymer", "SubstancePolymer")]
      SubstancePolymer = 155,         
      [EnumInfo("SubstanceProtein", "SubstanceProtein")]
      SubstanceProtein = 156,         
      [EnumInfo("SubstanceReferenceInformation", "SubstanceReferenceInformation")]
      SubstanceReferenceInformation = 157,         
      [EnumInfo("SubstanceSourceMaterial", "SubstanceSourceMaterial")]
      SubstanceSourceMaterial = 158,         
      [EnumInfo("SubstanceSpecification", "SubstanceSpecification")]
      SubstanceSpecification = 159,         
      [EnumInfo("TerminologyCapabilities", "TerminologyCapabilities")]
      TerminologyCapabilities = 160,         
      [EnumInfo("VerificationResult", "VerificationResult")]
      VerificationResult = 161,         
                       
  }
}



